baseURL: 'https://sergds.ga'
languageCode: 'ru-ru'
title: 'SergDS'
theme: "PaperMod"


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: SergDS
  description: "SergDS"
  keywords: [Homepage]
  author: sergds
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false
  favicon: "/favicon.ico"
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: false
  showtoc: false
  tocopen: false

defaultContentLanguage: ru
languages:
  ru:
    menu:
      main:
        - identifier: downloads
          name: "Загрузки"
          url: /downloads/
          weight: 10
        - identifier: home
          name: "Домашняя страница"
          url: /
          weight: 5
    title: SergDS
    weight: 1
  en:
    menu:
      main:
        - identifier: downloads
          name: Downloads
          url: /downloads/
          weight: 10
        - identifier: home
          name: Home
          url: /
          weight: 5
    title: SergDS
    weight: 2

